spring.application.name=relleno

#Configurar atributos para mi db
spring.datasource.url=jdbc:mysql://localhost:3306/keso_pasteleria?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuracion de la accion de JPA
spring.jpa.hibernate.ddl-auto=update

# Logs para ver informacion de las queries de JPA (dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true